# autolabeler:
#   - label: feature
#     branch:
#       - '/^feat(ure)?[/-].+/'
#   - label: bug
#     branch:
#       - '/^fix[/-].+/'
#   - label: chore
#     branch:
#       - '/^chore[/-].+/'
#   - label: refactor
#     branch:
#       - '/(refactor|refactoring)[/-].+/'
#   - label: enhancement
#     branch:
#       - '/doc(umentation)[/-].+/'
#     files:
#       - '*.md'
#   - label: enhancement
#     branch:
#       - '/(enhancement|improve)[/-].+/'

# ref : 正規表現
# https://murashun.jp/article/programming/regular-expression.html

# Added
# Add new features.
# Changed
# Change existing functionality.
# Deprecated
# Mark as soon-to-be removed features.
# Fixed
# Remove features.
# Others
# In case of vulnerabilities.
# Security 
 
autolabeler:
# Added
  - label: 'Added'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
# Changed
  - label: 'Changed'
    branch:
      # fix/3桁以上の文字列
      - '/fix\/.+/'
    title:
      # fix/文字や数値(大文字と小文字を区別しません。)
      - '/fix/i'
  - label: 'duplicate'
    branch:
      # feature/3桁以上の文字列
      - '/feature\/.+/'
    body:
      # JIRA- 1桁の全角数字 or 1 ～ 4 桁の半角数字
      - '/JIRA-[0-9]{1,4}/'

name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Breaking change'
    include-labels:
      - 'bug'
  - title: 'Features'
    labels:
      - 'Added'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'bug'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'Refactor'
    labels:
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
#   $CHANGES

commitish: master