# autolabeler:
#   - label: feature
#     branch:
#       - '/^feat(ure)?[/-].+/'
#   - label: bug
#     branch:
#       - '/^fix[/-].+/'
#   - label: chore
#     branch:
#       - '/^chore[/-].+/'
#   - label: refactor
#     branch:
#       - '/(refactor|refactoring)[/-].+/'
#   - label: enhancement
#     branch:
#       - '/doc(umentation)[/-].+/'
#     files:
#       - '*.md'
#   - label: enhancement
#     branch:
#       - '/(enhancement|improve)[/-].+/'

# Added
# Add new features.
# Changed
# Change existing functionality.
# Deprecated
# Mark as soon-to-be removed features.
# Fixed
# Remove features.
# Others
# In case of vulnerabilities.
# Security 

autolabeler:
  - label: 'Added'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'Added'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'Added'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'

name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Breaking change'
    labels:
      - 'Breaking Change'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'bug'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
  - title: 'Refactor'
    labels:
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  