@startmindmap
title 面接

header
あ
endheader

* 人材

** 弊社の開発環境とマッチしている
*** 属人性が高い業務が多いので、すぐ聞いてくれる人(無駄なことに時間費やすから)
*** 幅広い好奇心が必要

** ポテンシャル（成長）
*** フォロワーシップ
**** クリティカル・シンキング
**** 積極的関与

*** 楽しさを見いだせるか

*** 個人の成果ではなく組織の成果を考える人（早期離職の可能性減）

** 僕が働きたい
*** 共有する人
*** 新しい情報を教えてくれる人


' ITエンジニアって〇〇さんにとってなんですか？

' わからないふりをして聞いてみる

' 長所と短所を聞いてみる




@endmindmap