@startmindmap
title  interview

header
interview
endheader

* 人材

** 弊社の開発環境とマッチしている
*** 属人性が高い業務が多いので、すぐ聞いてくれる人(無駄なことに時間費やすから)
*** 幅広い好奇心が必要

** ポテンシャル（成長）
*** フォロワーシップ
**** クリティカル・シンキング
**** 積極的関与

*** 楽しさを見いだせるか

*** 個人の成果ではなく組織の成果を考える人（早期離職の可能性減）

** 僕が働きたい
*** 共有する人
*** 新しい情報を教えてくれる人


' https://saponet.mynavi.jp/column/detail/20210507125642.html
' ITエンジニアって〇〇さんにとってなんですか？
' わからないふりをして聞いてみる


' https://news.livedoor.com/article/detail/18777246/
' 自己評価が強い人を見抜くにはどうすればいいのだろう。
' 中途採用なら「これまでに全力で取り組んだ仕事とその達成度を教えてください」
' という質問で見抜けると冨樫氏は言う。
' 客観的に評価できる人は『毎月何件成約しました』といった『事実』を示します。
' 答えが見解にすぎないのか、それとも事実を正確に示すのかを見ていくだけで、
' 自己評価の度合いを測定できます」

' 新卒の場合は、通っていた大学のいい点・悪い点という質問
' 批判の割合を測るとわかりやすい。批判のほうが一方的に多ければ要注意だ。
' 「中途採用の場合は、転職理由を深掘りしていくのに尽きます。
' 面接の攻略本を読んできて、最初は優等生的なことを述べますが『ということは？』『つまり？』と切り込んでいくと、
' 次第にネタが尽きて自社批判になっていきます。そこで組織内位置認識の弱さが露呈するわけです。
' 新卒の場合は『大学のいい点、悪い点を言ってください』や『地元のいい点、悪い点を言ってください』という質問を投げかけると本音が出てきます。
' 所属してきた集団の批判の割合が多い人には気をつけろということです」

@endmindmap