@startmindmap
title 結論、Python Fast apiがよき

フロントエンド
spaかどうか、

awsに聞くこと。
弊社ecサイトの顧客管理画面を作成していて、
バックエンドAPIを構築してます。
そのサーバーに置きたいので、教えて欲しい。

安くすませたい、
そこまで性能は求めてない
ec2
ファーゲート

header
Fast api
🔃 コードを書くとSwagger UIが自動生成される
✅ 型安全
💨 高速
endheader

〇タイプスクリプト
* すでに使っている言語
* TyepScript 動的型付け
** シングルスレッドの性質
' SPA(SEOに不利)実装するならJSとの親和性が高いのでありコードがすでにある。
' https://zenn.dev/joanofarc/books/085bbef9ea7323/viewer/44a1f3#single-page-application-(spa)-とは？

** ユースケース
*** バグのない、セキュアでメンテナンスが容易なWebベースのソリューションのためにJavaScriptでのフルスタック開発が必要となる場合
*** Webベースのソリューションの開発コストを大幅に削減したい
*** 多数のユーザーからのリクエストに対応するプログラムを作成しようとしている場合

▲ GO 動的型付け
** クリーンアーキテクチャとの相性良い（フレームワークに依存しない）
** フレームワークに依存しないクリーンアーキテクチャ
** 軽量で保守しやすく（コーディングの差が起きにくい）高速なアプリケーション

◎ Python 静的型付け
** メリット
*** 汎用のプログラム言語、柔軟で、豊富なライブラリーがあるため、幅広い分野で使える
*** aiに活用できる（CIでカバーか）
*** MT５との連携
*** モチベーションアップ
後ほどデータ分析できる。
apiドキゅメンと自動生成できる
opt もPython apiを使える

** デメリット
*** 可読性/保守性が低くなりやすい（CIでカバーか）
*** 動作が遅いこと。（Fastapiでカバー）
*** 静的型付けなので、大規模なアプリ開発には向かない

' 失敗に学ぶ技術選定－Pythonでの中規模開発がクラッシュした話
' https://www.notion.so/Python-docs-09c7edd3430a46d0866215e639e653ed

* PHP 静的型付け
** 学習コスト低い

* C,C## 動的型付け
** 学習コスト低い

*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
