@startmindmap
title →筋道としての論理　↓言葉としての論理

header
　チェックリスト（MECEの最後）に対して直感を働かせる
  バカの壁が入らない（考えていない部分をなくす）
  頭の中にアイデアはあるがうまく引き出せないをなくす
endheader

* 設計
** RDB設計 
*** アンチパターン 
**** 主キーが設定されていないテーブルを作ってはイケナイ(レコードを一意に選択することができなくなります。)
**** テーブルによって同じデータでも列名が違う列を作ってはイケナイ
**** 一つの列にカンマなどで区切り複数の値を格納してはイケナイ
**** 日付データを数値型や文字列型のカラムに格納してはイケナイ
**** BLOB型で安易にバイナリデータを格納してはイケナイ
**** ありとあらゆる列にインデックスを付与してはイケナイ
**** 「区分」や「フラグ」という名の列名を作成してはイケナイ(必ず「○○区分」や「○○フラグ」のように何の区分なのか、何のフラグなのかを列名でしっかりと定義)
**** 将来の拡張に備えて予め予備カラム作ってはイケナイ
' https://www.depthbomb.net/?p=6334

*** 命名規則 

** NOsql


* Code
** リファクタリング
*** 関心の分離
*** クリーンアーキテクチャ
**** DDD
**** オブジェクト指向

*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap