@startmindmap
title issuedriven

header
あ
endheader

* 人材
* 「問題を解くより問題を見極める
* 「解の質を上げる」より「イシューの質を上げる」
* 「知れば知るほど知恵が湧く」より「知り過ぎるとバカになる」
* 「１つひとつを速くやる」より「やることを削る」
* 「数字のケタ数にこだわる」より「答えが出せるかにこだわる」




@endmindmap