' PlantUML: Preview Current
' PlantUML: Export Current Diagrams
' MacOS : 
' brew install graphviz
' brew install plantuml
' Chromeでは表示中のテキストをUML画像にする拡張が。使い方はこちらに。GitHub上でもこれで見れるね。
' https://chrome.google.com/webstore/detail/plantuml-viewer/legbfeljfbjgfifnkmpoajgpgejojooj?hl=ja
' Icon :
' https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites/blob/master/sprites-list.md

@startuml test

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/flask.puml
!includeurl SPRITESURL/kafka.puml
!includeurl SPRITESURL/kotlin.puml
!includeurl SPRITESURL/cassandra.puml
!includeurl SPRITESURL/github-icon.puml
!includeurl SPRITESURL/slack-icon.puml

title Sysyte

skinparam monochrome false

SP_GITHUB-ICON(dicon) #White {
      test
}

' 利用するアイコンを宣言
cloud github-icon{
     node LoadBalancer as lb
     node Application as app1
     node Application as app2
     database DB as db
   }


rectangle "<$kotlin>\ndaemon" as daemon
database "<$cassandra>" as cassandra
database "<$github-icon>" as cassandra
database "<$github-icon>" as cassandra




webapp -> kafka
kafka -> daemon
daemon --> cassandra 

@enduml