name: test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:            
      - name: Slack Notification
        run: |
          ipconfig
          curl https://www.google.com/ 
